"""
Sentiment timeline page — average sentiment scores over time.

Reads from Sentiment/sentiment_results.csv (generated by sentiment.py).
Groups individual article scores by month (YYYY-MM extracted from filename)
and plots the averaged negative / neutral / positive scores as a line chart.

This replaces the blocking matplotlib window in Sentiment/timeline.py with
an interactive Plotly figure embedded in the dashboard.

NOTE: This page does NOT re-run the sentiment model. Run sentiment.py first
to generate (or update) sentiment_results.csv.
"""

import re
from datetime import datetime
from pathlib import Path

import dash
import pandas as pd
import plotly.express as px
from dash import dcc, html

dash.register_page(__name__, path="/sentiment", name="Sentiment Timeline")

# ── Load and process data ────────────────────────────────────────────────────
_CSV_PATH = Path(__file__).resolve().parents[1] / "Sentiment" / "sentiment_results.csv"


def _build_timeline(csv_path: Path) -> pd.DataFrame | None:
    if not csv_path.exists():
        return None

    df = pd.read_csv(csv_path)

    # One representative row per file:
    # - use the "avg" row for multi-chunk files
    # - use the single row for single-chunk files
    df["_is_avg"] = df["chunk"].astype(str) == "avg"
    per_file = (
        df.sort_values("_is_avg", ascending=False)
        .drop_duplicates(subset=["file"], keep="first")
        .drop(columns=["_is_avg"])
    )

    # Extract YYYY-MM date from filename (matches "2023-01.txt", "2026-02-5.txt", etc.)
    def _extract_date(filename: str) -> datetime | None:
        m = re.search(r"(\d{4}-\d{2})", str(filename))
        if m:
            try:
                return datetime.strptime(m.group(1), "%Y-%m")
            except ValueError:
                return None
        return None

    per_file = per_file.copy()
    per_file["date"] = per_file["file"].apply(_extract_date)
    per_file = per_file.dropna(subset=["date"])

    if per_file.empty:
        return None

    # Average across all files in the same month, then compute a single score:
    # score = positive - negative, ranging from -1 (very negative) to +1 (very positive)
    monthly = (
        per_file.groupby("date")[["negative", "neutral", "positive"]]
        .mean()
        .reset_index()
        .sort_values("date")
    )
    monthly["score"] = monthly["positive"] - monthly["negative"]
    return monthly


_timeline = _build_timeline(_CSV_PATH)

# ── Layout ───────────────────────────────────────────────────────────────────
if _timeline is None:
    layout = html.Div(
        [
            html.H2("Sentiment Timeline"),
            html.P(
                [
                    "No sentiment data found. Run ",
                    html.Code("python Sentiment/sentiment.py"),
                    " first to generate sentiment_results.csv.",
                ],
                style={"color": "#888"},
            ),
        ],
        style={"padding": "16px"},
    )

else:
    _n_months = len(_timeline)

    _fig = px.line(
        _timeline,
        x="date",
        y="score",
        markers=True,
        labels={"date": "Month", "score": "Sentiment Score"},
        title="Monthly Sentiment Score — Education News",
    )
    # Colour points by sign: green above zero, red below
    _fig.update_traces(
        line_color="#555",
        marker=dict(
            color=_timeline["score"].apply(lambda s: "#27ae60" if s >= 0 else "#c0392b"),
            size=8,
        ),
    )
    # Neutral reference line at y=0
    _fig.add_hline(y=0, line_dash="dash", line_color="#aaa", line_width=1)
    _fig.update_layout(
        xaxis=dict(tickformat="%Y-%m"),
        yaxis=dict(range=[-1, 1], tickformat=".1f", title="← negative   |   positive →"),
        margin=dict(l=40, r=20, t=60, b=40),
        hovermode="x unified",
    )

    layout = html.Div(
        [
            html.H2("Sentiment Timeline"),
            html.P(
                f"{_n_months} monthly data points (Jan 2023 – Jun 2024, education_news folder).",
                style={"color": "#555", "fontSize": "0.9rem"},
            ),
            dcc.Graph(figure=_fig, style={"height": "65vh"}),
            html.P(
                [
                    "Note: current data is pre-populated from the education_news folder. "
                    "Replace by running ",
                    html.Code("python Sentiment/sentiment.py Sentiment/education_news"),
                    " once the model dependencies are installed.",
                ],
                style={"fontSize": "0.85rem", "color": "#888", "marginTop": "8px"},
            ),
        ],
        style={"padding": "16px"},
    )
